[versions]
agp = "9.0.0"
android-sdk="36"
android-min-sdk="26"
javapoet = "1.13.0"
kotlin = "2.3.0"
kotlinx-coroutines-test = "1.10.2"
mockito = "5.21.0"
mockito-kotlin = "6.2.3"
ktlint = "14.0.1"
com-google-devtools-ksp = "2.3.5"
easylauncher = "6.4.1"
core-ktx = "1.17.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"
lifecycle-runtime-ktx = "2.10.0"
activity-compose = "1.12.3"
compose-destinations = "2.3.0"
material-icons = "1.7.8"
androidx-test = "1.7.0"
security-crypto = "1.1.0"
moshi = "1.15.2"
dagger-hilt = "2.59.1"
hilt-navigation = "1.3.0"
compose-material3 = "1.5.0-alpha13"
play-services = "21.3.0"
play-app-update = "2.1.0"
compose = "1.11.0-alpha04"
room = "2.8.4"
firebase-crashlytics = "20.0.4"
google-gms-google-services = "4.4.4"
google-firebase-crashlytics = "3.0.6"
okhttp = "5.3.2"
retrofit = "3.0.0"

[libraries]
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
android-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger-hilt" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons" }
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-destinations-core = { group = "io.github.raamcosta.compose-destinations", name = "core", version.ref = "compose-destinations" }
compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "compose-destinations" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger-hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger-hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services" }
play-appupdate = { group = "com.google.android.play", name = "app-update", version.ref = "play-app-update" }
play-appupdate-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "play-app-update" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebase-crashlytics" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }

[plugins]
androidx-room = { id = "androidx.room", version.ref = "room" }
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools-ksp" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "google-gms-google-services" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "google-firebase-crashlytics" }
easylauncher = { id = "com.starter.easylauncher", version.ref = "easylauncher" }

[bundles]